#!/bin/zsh

#
# Utility tool for my way of working with git.
#

# Commands should be ran inside a git directory.
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || return

if [ "$#" -eq 0 ]; then
  # No arguments passed to the `g` command. Display some information about the
  # current state of the repo.
  git status --short --branch --show-stash

  # List all the files that are hidden from git. I will still notice them, but
  # won't commit them easily.
  if hidden=$(git ls-files -v | grep '^[[:lower:]]'); then
    printf '%s' "$hidden" | xargs -n 2 printf ' \033[38;5;8m%s %s\033[0m\n' 
  fi
fi
