#!/bin/zsh

#
# Utility tool for my way of working with git.
#

if [ -t 1 ]; then
  BOLD='\033[1m'
  RESET='\033[0m'
  HIDDEN='\033[38;5;8m'
else
  BOLD=''
  RESET=''
  HIDDEN=''
fi

if [ "$#" -eq 0 ]; then
  git rev-parse --is-inside-work-tree >/dev/null 2>&1 || return

  # No arguments passed to the `g` command. Display some information about the
  # current state of the repo.
  git status --short --branch --show-stash

  # List all the files that are hidden from git. I will still notice them, but
  # won't commit them easily.
  if hidden=$(g hidden); then
    printf '%s' "$hidden" | xargs -n 2 printf " $HIDDEN%s %s$RESET\n"
  fi
elif [ "$1" = 'hide' ]; then
  shift; git update-index --assume-unchanged "$@"
elif [ "$1" = 'track' ]; then
  shift; git update-index --no-assume-unchanged "$@"
elif [ "$1" = 'hidden' ]; then
  shift; git ls-files -v | grep "^[[:lower:]]"
else
  git "$@"
fi
