#!/bin/sh

header="$(printf '%*s\n' "$(tput cols)" ' ' | tr ' ' '-')"
prefix='---'

title="$1"

prefix_length=$(( ${#title} + ${#prefix} ))

suffix_length=$(( ${#header} - prefix_length ))
suffix="$(printf '%*s\n' "$suffix_length" ' ' | tr ' ' '-')"

printf -- '%s\033[1m%s\033[0m%s\n' "$prefix" "$title" "$suffix"
